spring:

  application:

    name: mail-service

  servlet:

    multipart:

      max-file-size: 10MB

      max-request-size: 25MB

  mail:

    host: ${SMTP_SERVER:smtp.gmail.com}

    port: ${MAIL_PORT:587}

    username: ${MAIL_USERNAME}

    password: ${MAIL_PASSWORD}

    properties:

      mail:

        smtp:

          auth: true

          starttls:

            enable: true

            required: true

server:

  port: ${SERVER_PORT:8086}

logging:

  level:

    com.julian.email: DEBUG

    org.springframework.mail: DEBUG

springdoc:

  api-docs:

    path: /v3/api-docs

  swagger-ui:

    path: /swagger-ui.html

    operations-sorter: method

    tags-sorter: alpha